resources:
- ../../../base/node
images:
- name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  # Don't change stable image without changing pdImagePlaceholder in
  # test/k8s-integration/main.go
  newName: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  newTag: "v0.5.1-gke.0"
- name: gke.gcr.io/csi-node-driver-registrar
  newName: gke.gcr.io/csi-node-driver-registrar
  newTag: "v1.1.0-gke.0"
