resources:
- ../../../base/controller
images:
- name: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  # Don't change stable image without changing pdImagePlaceholder in
  # test/k8s-integration/main.go
  newName: gke.gcr.io/gcp-compute-persistent-disk-csi-driver
  newTag: "v0.5.1-gke.0"
- name: gke.gcr.io/csi-provisioner
  newName: gke.gcr.io/csi-provisioner
  newTag: "v1.2.1-gke.0"
- name: gke.gcr.io/csi-attacher
  newName: gke.gcr.io/csi-attacher
  newTag: "v1.2.0-gke.0"
