# arrays without strategic patch merge defined need to be appended
# using jsonpatch
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/jsonpatch.md
- op: add
  path: /rules/-
  value:
    apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]

- op: add
  path: /rules/-
  value:
    apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]
